language: python
python:
  - 3.4
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libnetcdf-dev
before_install:
  - nvm install 4
install:
  - pip install -i http://tools.pacificclimate.org/pypiserver/ ./backend
  - cd client && npm install
# command to run tests
script: py.test -v backend
