version: '2'
services:
  backend:
    build: backend
    name: backend
    ports:
     - "${BACKEND_PORT}:8000"
    environment:
      - MDDB_DSN

  frontend:
    build: frontend
    name: frontend
    ports:
     - "${FRONTEND_PORT}:8080"
    environment:
     - CE_BACKEND_URL="${PUBLIC_URL}:${BACKEND_PORT}/api"

